import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title:
    "mkazm's site or smth like that, idk i lowkey suck at frontend, cuz i aint no frontas so its ugly as hell, also now that got long i should probably stop writing, but i wonder how long this can be, and is there a limit like google not allowing it or smth like that, also i use arch btw",
  description: "Generated by me and some of my insanity",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
